### ISSUE TITLE
中青actions，报错这么一个错误

### ISSUE THREAD

**Issue by 965962591** [Sunert/Scripts#25]
开始【中青看点1】
(node:2359)UnhandledPromiseRejectionMarning: TypeError:Cannot read property 'read_score’of undefined
at/home/runner/work/Scripts-1/Scripts-1/Task/youth.js:497:31
at got.post.then.message(/home/runner/work/Scripts-1/Scripts-1/Task/youth.js:685:5694)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use ~node --trace-warnings ...' to show where the warning was created)
rejections=strict'(see https://nodejs.ong/api/cli.htmItcli_unhandled_rejections_mode).(rejection id: 1)
Node.js process with a non-zero exit code.
(ode:.239)UnhandledProwiselejectionMarning: Uhbadled pomise rejection.mis error originated eitr by thorowing inside of an async function without a catth
block, o by rejecting a promise wich was not handled with .catch). o terminate the node processon unhadled promise rejection,use the ClI flag "--umhadled
(node:259)[DPNO18] DeprecationMarning: Uhbandld promise rejections are deprecated. In the future, promise rejections that are not handld will teminate the

**Comment by Maccrack** [comment]
兄弟想问一下你是用哪个软件抓的cookie

**Comment by Crazyguy2020** [comment]
> 开始【中青看点1】
> (node:2359)UnhandledPromiseRejectionMarning: TypeError:Cannot read property 'read_score’of undefined
> at/home/runner/work/Scripts-1/Scripts-1/Task/youth.js:497:31
> at got.post.then.message(/home/runner/work/Scripts-1/Scripts-1/Task/youth.js:685:5694)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use ~node --trace-warnings ...' to show where the warning was created)
> rejections=strict'(see https://nodejs.ong/api/cli.htmItcli_unhandled_rejections_mode).(rejection id: 1)
> Node.js process with a non-zero exit code.
> (ode:.239)UnhandledProwiselejectionMarning: Uhbadled pomise rejection.mis error originated eitr by thorowing inside of an async function without a catth
> block, o by rejecting a promise wich was not handled with .catch). o terminate the node processon unhadled promise rejection,use the ClI flag "--umhadled
> (node:259)[DPNO18] DeprecationMarning: Uhbandld promise rejections are deprecated. In the future, promise rejections that are not handld will teminate the

这个报错是怎么解决的？

**Comment by JackBai8659** [comment]
你是不是发错人了，我也不清楚啊 在2021年02月15日 10:13，Crazyguy2020 写道： 



开始【中青看点1】

(node:2359)UnhandledPromiseRejectionMarning: TypeError:Cannot read property 'read_score’of undefined

at/home/runner/work/Scripts-1/Scripts-1/Task/youth.js:497:31

at got.post.then.message(/home/runner/work/Scripts-1/Scripts-1/Task/youth.js:685:5694)

at processTicksAndRejections (internal/process/task_queues.js:93:5)

(Use ~node --trace-warnings ...' to show where the warning was created)

rejections=strict'(see https://nodejs.ong/api/cli.htmItcli_unhandled_rejections_mode).(rejection id: 1)

Node.js process with a non-zero exit code.

(ode:.239)UnhandledProwiselejectionMarning: Uhbadled pomise rejection.mis error originated eitr by thorowing inside of an async function without a catth

block, o by rejecting a promise wich was not handled with .catch). o terminate the node processon unhadled promise rejection,use the ClI flag "--umhadled

(node:259)[DPNO18] DeprecationMarning: Uhbandld promise rejections are deprecated. In the future, promise rejections that are not handld will teminate the



这个报错是怎么解决的？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Sunert/Scripts/issues/25#issuecomment-778895595",

"url": "https://github.com/Sunert/Scripts/issues/25#issuecomment-778895595",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
